language: php
sudo: false
env:
  global:
    - SERVICE_ENV=test
    - SERVICE_HOST=localhost:8080
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5432
    - POSTGRES_DB=postgres
    - POSTGRES_TEST_DB=postgres-test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mysecretpassword
    - REDIS_HOST=localhost
    - REDIS_PORT=6379
    - REDIS_TEST_DB=0
php:
  - '7.1'
services:
  - postgres
  - redis-server
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - composer run-script --dev init-database
  - vendor/bin/doctrine-migrations migrations:migrate --db-configuration=config/test-migrations.php --no-interaction
  - nohup php -S localhost:8080 -t web web/index-test.php 1>/dev/null 2>&1 &
  - PHP_SERVER_PID=$!
script:
  - vendor/bin/codecept run
after_script:
  - kill -3 $PHP_SERVER_PID
