version: '3.2'
services:
  user:
    build:
      context: ./env/docker/nginx
    image: user/nginx:v1
    container_name: user-nginx
    ports:
    - '8080:80'
    env_file:
    - ./env/docker/nginx/env
    volumes:
    - ./:/usr/share/nginx/service
    depends_on:
    - php-fpm
  php-fpm:
    build:
      context: ./env/docker/php-fpm
    image: user/php-fpm:v1
    container_name: user-php-fpm
    env_file:
    - ./env/docker/php-fpm/env
    - ./env/docker/nginx/env
    - ./env/docker/postgres/env
    - ./env/docker/redis/env
    volumes:
    - ./:/usr/share/nginx/service
    depends_on:
    - postgres
    - redis
  postgres:
    image: postgres:9.6
    container_name: user-postgres
    ports:
    - '5432:5432'
    env_file:
    - ./env/docker/postgres/env
  redis:
    image: redis:3.2
    container_name: user-redis
    env_file:
    - ./env/docker/redis/env
